stages:
  - build
  - test

build:
  stage: build
  image:
    name: sensirion/embedded-ci:2.3.0
  tags: [linux, docker]
  script:
    - make

test:
  stage: test
  image: registry.gitlab.sensirion.lokal/sensirion/docker/docker-rpi-testbed:1.2.0
  tags: [mso-sw-testbed-2]
  script:
    - cd tests/
    - make test
